spring:
  application:
    name: sensor-data-collector

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
