sensors:
  - apiKey: abc
    location: location1
  - apiKey: def
    location: location2

influxdb:
  measurements:
    temperature: temp
    air-quality: aqi
    air-pressure: airpressure

context:
  initializer:
    classes: info.szadkowski.sensor.data.collector.DependenciesInitializer
